# Site wide configuration

title: Site Title
locale: en_US
logo: # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Nevrez Imamoglu
  avatar: bio-photo.jpg
  bio: "I am currently employed as a Senior Researcher at National Institute of Advanced Industrial Science and Technology (AIST), Tokyo, Japan since April 2016. Before AIST, I was with RIKEN Brain Science Institute as a Researcher & JSPS Foreign Postdoctoral Fellow in 2015-2016. I received the Ph.D. degree from Chiba University (2015), Japan, with a Japanese Government scholarship (MEXT). I was also with School of Computer Eng., Nanyang Technbological University, Singapore as a Research Associate 2010-2011. I received the M.S. and B.S. degrees from TOBB University of Economics and Technology (Ankara, Turkey) and Cankaya University (Ankara, Turkey) in 2010 and 2007. My research interests include applications of computer vision and machine learning, recently with special interests on deep learning for multi-modal or multi-temporal signal/image analysis, visual attention (saliency detection), classification/object detection/segmentation on various sensory data (3D, optical, multispectral, hyperspectral). Please contact me if you are interested in Post-doc, internship, research assitantship with me or our team."
  email: #emailaddress
  # Do not include the @ symbol in your Twitter username
  twitter: #username
  linkedin: nevrez
  github: nevrez
  orcid: 0000-0002-2661-599X
  researchgate: Nevrez-Imamoglu
  mendeley: #username
  google:
    plus: #username
    analytics:
    verify:
    scholar: #id
  facebook: #username
  instagram: #username
  bing-verify:
  stackoverflow: #123456/username from a "https://stackoverflow.com/users/123456/username" link
  xing: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  disqus-shortname:

# The following adjust the accents for your site. If you would like to further edit colors, fonts, font sizes, etc.
# you may do so in _sass/variables.scss
highlight-color: '#CC0000'
lowlight-color: '#000'

  # NOTE: If you would like your site to be licensed under a creative commons license, uncomment the 'yes' next to the type of license you wish to use.
creative-commons:
  cc-by: #yes
  cc-by-nc: #yes

#DO NOT EDIT BEYOND THIS POINT
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
